# Generated by Django 6.0.3 on 2026-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_delay', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
        ),
    ]
