# Generated by Django 6.0.3 on 2026-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_garage', models.BooleanField()),
                ('is_light', models.BooleanField()),
                ('is_exhaust', models.BooleanField()),
            ],
        ),
    ]
