# Generated by Django 6.0.3 on 2026-03-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='garage_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
