# Generated by Django 6.0.2 on 2026-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_garage_garage_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='is_garage_close',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='is_garage_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
